services:
  app:
    container_name: talep-takip-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/talep_takip_db?schema=public&connection_limit=5
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_SECRET=antigravity_secret_32_chars_long_random
      - AUTH_TRUST_HOST=true
    depends_on:
      - postgres
    networks:
      - talep-takip-network

  nginx:
    image: nginx:alpine
    container_name: talep-takip-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - talep-takip-network

  certbot:
    image: certbot/certbot
    container_name: talep-takip-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - talep-takip-network

  postgres:
    container_name: talep-takip-db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: talep_takip_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - talep-takip-network

volumes:
  postgres_data:
  certbot_conf:
  certbot_www:


networks:
  talep-takip-network:
    driver: bridge
