
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.TalepScalarFieldEnum = {
  id: 'id',
  tarih: 'tarih',
  barkod: 'barkod',
  konu: 'konu',
  gerekce: 'gerekce',
  durum: 'durum',
  ilgiliKisiId: 'ilgiliKisiId',
  birimId: 'birimId',
  bildirimEmail: 'bildirimEmail',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  sorumluId: 'sorumluId'
};

exports.Prisma.TalepKalemScalarFieldEnum = {
  id: 'id',
  aciklama: 'aciklama',
  detay: 'detay',
  miktar: 'miktar',
  birim: 'birim',
  talepId: 'talepId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SiparisScalarFieldEnum = {
  id: 'id',
  tarih: 'tarih',
  barkod: 'barkod',
  aciklama: 'aciklama',
  durum: 'durum',
  talepId: 'talepId',
  birimId: 'birimId',
  yonetmelikId: 'yonetmelikId',
  alimYontemiId: 'alimYontemiId',
  tedarikciId: 'tedarikciId',
  degerlendirmeFormTipiId: 'degerlendirmeFormTipiId',
  rfqId: 'rfqId',
  teklifId: 'teklifId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DegerlendirmeTokenScalarFieldEnum = {
  id: 'id',
  token: 'token',
  siparisId: 'siparisId',
  kullanildi: 'kullanildi',
  createdAt: 'createdAt'
};

exports.Prisma.FaturaScalarFieldEnum = {
  id: 'id',
  faturaNo: 'faturaNo',
  tutar: 'tutar',
  vadeTarihi: 'vadeTarihi',
  odemeDurumu: 'odemeDurumu',
  siparisId: 'siparisId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SozlesmeScalarFieldEnum = {
  id: 'id',
  sozlesmeNo: 'sozlesmeNo',
  baslangicTarihi: 'baslangicTarihi',
  bitisTarihi: 'bitisTarihi',
  dosyaYolu: 'dosyaYolu',
  siparisId: 'siparisId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PersonelScalarFieldEnum = {
  id: 'id',
  adSoyad: 'adSoyad',
  unvan: 'unvan',
  email: 'email',
  telefon: 'telefon',
  aktif: 'aktif',
  birimId: 'birimId',
  isBirimYoneticisi: 'isBirimYoneticisi',
  createdAt: 'createdAt'
};

exports.Prisma.BirimScalarFieldEnum = {
  id: 'id',
  ad: 'ad',
  email: 'email',
  createdAt: 'createdAt'
};

exports.Prisma.YonetmelikScalarFieldEnum = {
  id: 'id',
  madde: 'madde',
  aciklama: 'aciklama',
  createdAt: 'createdAt'
};

exports.Prisma.AlimYontemiScalarFieldEnum = {
  id: 'id',
  ad: 'ad',
  createdAt: 'createdAt'
};

exports.Prisma.TedarikciScalarFieldEnum = {
  id: 'id',
  ad: 'ad',
  yetkiliKisi: 'yetkiliKisi',
  telefon: 'telefon',
  email: 'email',
  adres: 'adres',
  vergiNo: 'vergiNo',
  vergiDairesi: 'vergiDairesi',
  aktif: 'aktif',
  durum: 'durum',
  basvuruTarihi: 'basvuruTarihi',
  onayTarihi: 'onayTarihi',
  onaylayanId: 'onaylayanId',
  logo: 'logo',
  aciklama: 'aciklama',
  kategoriId: 'kategoriId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TedarikciKategoriScalarFieldEnum = {
  id: 'id',
  ad: 'ad',
  aciklama: 'aciklama',
  aktif: 'aktif',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TedarikciKategoriOnayScalarFieldEnum = {
  id: 'id',
  tedarikciId: 'tedarikciId',
  kategoriId: 'kategoriId',
  durum: 'durum',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TedarikciDegerlendirmeScalarFieldEnum = {
  id: 'id',
  tarih: 'tarih',
  teslimatPuani: 'teslimatPuani',
  kalitePuani: 'kalitePuani',
  fiyatPuani: 'fiyatPuani',
  iletisimPuani: 'iletisimPuani',
  genelPuan: 'genelPuan',
  yorum: 'yorum',
  tedarikciId: 'tedarikciId',
  siparisId: 'siparisId',
  createdAt: 'createdAt'
};

exports.Prisma.DegerlendirmeFormuTipiScalarFieldEnum = {
  id: 'id',
  ad: 'ad',
  aciklama: 'aciklama',
  aktif: 'aktif',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DegerlendirmeGrubuScalarFieldEnum = {
  id: 'id',
  kod: 'kod',
  ad: 'ad',
  agirlik: 'agirlik',
  sira: 'sira',
  formTipiId: 'formTipiId',
  createdAt: 'createdAt'
};

exports.Prisma.DegerlendirmeSorusuScalarFieldEnum = {
  id: 'id',
  kod: 'kod',
  soru: 'soru',
  sira: 'sira',
  grupId: 'grupId',
  createdAt: 'createdAt'
};

exports.Prisma.DegerlendirmeCevabiScalarFieldEnum = {
  id: 'id',
  puan: 'puan',
  aciklama: 'aciklama',
  soruId: 'soruId',
  formId: 'formId'
};

exports.Prisma.TedarikciDegerlendirmeFormuScalarFieldEnum = {
  id: 'id',
  tarih: 'tarih',
  degerlendiren: 'degerlendiren',
  tedarikciId: 'tedarikciId',
  formTipiId: 'formTipiId',
  siparisId: 'siparisId',
  genelPuan: 'genelPuan',
  sonuc: 'sonuc',
  createdAt: 'createdAt'
};

exports.Prisma.SystemSettingScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeklifTokenScalarFieldEnum = {
  id: 'id',
  token: 'token',
  talepId: 'talepId',
  tedarikciId: 'tedarikciId',
  rfqTedarikciId: 'rfqTedarikciId',
  olusturmaTarihi: 'olusturmaTarihi',
  sonGecerlilik: 'sonGecerlilik',
  kullanildiMi: 'kullanildiMi',
  kullanilmaTarihi: 'kullanilmaTarihi'
};

exports.Prisma.TeklifScalarFieldEnum = {
  id: 'id',
  tokenId: 'tokenId',
  talepId: 'talepId',
  tedarikciId: 'tedarikciId',
  hariciTedarikciAdi: 'hariciTedarikciAdi',
  toplamTutar: 'toplamTutar',
  paraBirimi: 'paraBirimi',
  teslimSuresi: 'teslimSuresi',
  gecerlilikSuresi: 'gecerlilikSuresi',
  notlar: 'notlar',
  olusturmaTarihi: 'olusturmaTarihi',
  durum: 'durum',
  turNo: 'turNo',
  vadeGun: 'vadeGun',
  rfqId: 'rfqId'
};

exports.Prisma.OdemePlaniScalarFieldEnum = {
  id: 'id',
  oran: 'oran',
  vadeGun: 'vadeGun',
  aciklama: 'aciklama',
  teklifId: 'teklifId',
  siparisId: 'siparisId',
  createdAt: 'createdAt'
};

exports.Prisma.TeklifKalemScalarFieldEnum = {
  id: 'id',
  teklifId: 'teklifId',
  talepKalemId: 'talepKalemId',
  rfqKalemId: 'rfqKalemId',
  birimFiyat: 'birimFiyat'
};

exports.Prisma.RFQScalarFieldEnum = {
  id: 'id',
  rfqNo: 'rfqNo',
  baslik: 'baslik',
  aciklama: 'aciklama',
  olusturmaTarihi: 'olusturmaTarihi',
  sonTeklifTarihi: 'sonTeklifTarihi',
  durum: 'durum',
  mevcutTur: 'mevcutTur',
  maksimumTur: 'maksimumTur',
  turBitisTarihi: 'turBitisTarihi',
  turDurumu: 'turDurumu',
  agirlikFiyat: 'agirlikFiyat',
  agirlikVade: 'agirlikVade',
  agirlikTeslimat: 'agirlikTeslimat',
  agirlikPerformans: 'agirlikPerformans',
  olusturanId: 'olusturanId',
  kategoriId: 'kategoriId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RFQKalemScalarFieldEnum = {
  id: 'id',
  rfqId: 'rfqId',
  talepId: 'talepId',
  talepKalemId: 'talepKalemId',
  miktar: 'miktar',
  bolunebilir: 'bolunebilir',
  createdAt: 'createdAt'
};

exports.Prisma.RFQTedarikciScalarFieldEnum = {
  id: 'id',
  rfqId: 'rfqId',
  tedarikciId: 'tedarikciId',
  gonderimTarihi: 'gonderimTarihi',
  durum: 'durum',
  createdAt: 'createdAt'
};

exports.Prisma.SiparisKalemSecimiScalarFieldEnum = {
  id: 'id',
  rfqKalemId: 'rfqKalemId',
  teklifId: 'teklifId',
  siparisId: 'siparisId',
  createdAt: 'createdAt'
};

exports.Prisma.AttachmentScalarFieldEnum = {
  id: 'id',
  fileName: 'fileName',
  filePath: 'filePath',
  fileType: 'fileType',
  fileSize: 'fileSize',
  relatedEntity: 'relatedEntity',
  entityId: 'entityId',
  createDate: 'createDate'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  title: 'title',
  message: 'message',
  type: 'type',
  link: 'link',
  isRead: 'isRead',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  password: 'password',
  role: 'role',
  personelId: 'personelId',
  tedarikciId: 'tedarikciId',
  isTedarikciAdmin: 'isTedarikciAdmin',
  createDate: 'createDate'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.TedarikciDavetScalarFieldEnum = {
  id: 'id',
  email: 'email',
  firmaAdi: 'firmaAdi',
  kategoriler: 'kategoriler',
  token: 'token',
  davetEdenId: 'davetEdenId',
  davetTarihi: 'davetTarihi',
  sonKullanmaTarihi: 'sonKullanmaTarihi',
  durum: 'durum',
  kullanilanTarih: 'kullanilanTarih'
};

exports.Prisma.TedarikciBelgeScalarFieldEnum = {
  id: 'id',
  tedarikciId: 'tedarikciId',
  tur: 'tur',
  dosyaAdi: 'dosyaAdi',
  dosyaUrl: 'dosyaUrl',
  yuklemeTarihi: 'yuklemeTarihi'
};

exports.Prisma.TedarikciIbanScalarFieldEnum = {
  id: 'id',
  tedarikciId: 'tedarikciId',
  bankaAdi: 'bankaAdi',
  iban: 'iban',
  varsayilan: 'varsayilan'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.TedarikciDurum = exports.$Enums.TedarikciDurum = {
  BEKLIYOR: 'BEKLIYOR',
  AKTIF: 'AKTIF',
  PASIF: 'PASIF',
  REDDEDILDI: 'REDDEDILDI'
};

exports.KategoriOnayDurum = exports.$Enums.KategoriOnayDurum = {
  BEKLIYOR: 'BEKLIYOR',
  ONAYLANDI: 'ONAYLANDI',
  REDDEDILDI: 'REDDEDILDI'
};

exports.DavetDurum = exports.$Enums.DavetDurum = {
  BEKLIYOR: 'BEKLIYOR',
  KULLANILDI: 'KULLANILDI',
  IPTAL_EDILDI: 'IPTAL_EDILDI',
  SURESI_DOLDU: 'SURESI_DOLDU'
};

exports.BelgeTuru = exports.$Enums.BelgeTuru = {
  VERGI_LEVHASI: 'VERGI_LEVHASI',
  ISO_BELGESI: 'ISO_BELGESI',
  IMZA_SIRKULERI: 'IMZA_SIRKULERI',
  TICARET_SICIL: 'TICARET_SICIL',
  DIGER: 'DIGER'
};

exports.Prisma.ModelName = {
  Talep: 'Talep',
  TalepKalem: 'TalepKalem',
  Siparis: 'Siparis',
  DegerlendirmeToken: 'DegerlendirmeToken',
  Fatura: 'Fatura',
  Sozlesme: 'Sozlesme',
  Personel: 'Personel',
  Birim: 'Birim',
  Yonetmelik: 'Yonetmelik',
  AlimYontemi: 'AlimYontemi',
  Tedarikci: 'Tedarikci',
  TedarikciKategori: 'TedarikciKategori',
  TedarikciKategoriOnay: 'TedarikciKategoriOnay',
  TedarikciDegerlendirme: 'TedarikciDegerlendirme',
  DegerlendirmeFormuTipi: 'DegerlendirmeFormuTipi',
  DegerlendirmeGrubu: 'DegerlendirmeGrubu',
  DegerlendirmeSorusu: 'DegerlendirmeSorusu',
  DegerlendirmeCevabi: 'DegerlendirmeCevabi',
  TedarikciDegerlendirmeFormu: 'TedarikciDegerlendirmeFormu',
  SystemSetting: 'SystemSetting',
  TeklifToken: 'TeklifToken',
  Teklif: 'Teklif',
  OdemePlani: 'OdemePlani',
  TeklifKalem: 'TeklifKalem',
  RFQ: 'RFQ',
  RFQKalem: 'RFQKalem',
  RFQTedarikci: 'RFQTedarikci',
  SiparisKalemSecimi: 'SiparisKalemSecimi',
  Attachment: 'Attachment',
  Notification: 'Notification',
  Account: 'Account',
  Session: 'Session',
  User: 'User',
  VerificationToken: 'VerificationToken',
  TedarikciDavet: 'TedarikciDavet',
  TedarikciBelge: 'TedarikciBelge',
  TedarikciIban: 'TedarikciIban'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
